title: "Nemediano"

author_name: Jorge Antonio García Galicia

description: >
  Soy Jorge García, aquí hay información acerca de mi, como: proyectos, currículum y publicaciones.

lang_name: Español

subscribe: Subscríbete

sitemap: Mapa de sitio

switch_lang: Switch to

localized_links:
  projects: projects
  publications: publications
  resume: resume
  test: test
