title: "Nemediano"

author_name: Jorge A. Garcia Galicia

description: >
  I'm Jorge Garcia, here you can find info about me, like projects, curriculum vitae and publications.

lang_name: English

subscribe: Subscribe

sitemap: Site map

localized_links:
  projects: proyectos
  publications: publicaciones
  resume: curriculum
